version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/tmp
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dreams?sslmode=disable
      - OLLAMA_HOST=http://ollama:11435
    depends_on:
      - db
      - ollama

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - server

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dreams
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ./scripts:/scripts
      - ollama_data:/root/.ollama
    command: sh -c "apk add --no-cache netcat-openbsd && /scripts/ollama-entrypoint.sh"

volumes:
  postgres_data:
  ollama_data:
