services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - images:/app/images
      - /app/tmp
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dreams?sslmode=disable
      - AI_API_HOST=http://ollama:11434
      - AI_MODEL_NAME=llava
      - GOFLAGS=-mod=mod
      - CGO_ENABLED=0
    depends_on:
      - db
      - ollama
    networks:
      - dreams-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: server
    # Run as root for development to avoid permission issues
    user: root

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
      - /app/node_modules
      - /app/.next
      - images:/app/public/images  # Make images available to the webapp
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - server
    networks:
      - dreams-network
    container_name: webapp

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dreams
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dreams-network
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ./scripts:/scripts
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "/scripts/ollama-entrypoint.sh"]
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    networks:
      - dreams-network
    container_name: ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  dreams-network:
    name: dreams-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  ollama_data:
  images: